name: "Check cherry-picks"
on:
  pull_request_target:
    branches:
     - 'release-*'
     - 'staging-*'

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'risicle'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        filter: blob:none
    - name: Check cherry-picks
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        ./maintainers/scripts/check-cherry-picks.sh "$BASE_SHA" "$HEAD_SHA"
